# The URL the site will be built for
base_url = "https://multilingual-llm.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
title = "MLLM"
theme = "DeepThought"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
# Enable external libraries
katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
  { code = "en", nav_items = [
    { url = "$BASE_URL/", name = "Home" },
    { url = "$BASE_URL/paperlist", name = "Paperlist", link_list = [
      { url = "$BASE_URL/parameter_tuned_alignment", name = "Parameter-Tuned Alignment" },
      { url = "$BASE_URL/parameter_frozen_alignment", name = "Parameter-Frozen Alignment" },
    ] },
    { url = "$BASE_URL/trends_future_work", name = "Trends & Future Work" },
    { url = "$BASE_URL/resources", name = "Data Resources" },
    { url = "$BASE_URL/contact", name = "Contact" },
  ] },
]

# Add links to favicon, you can use https://realfavicongenerator.net/ to generate favicon for your site
[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "DeepThought"
# avatar = "/images/avatar.png"

# Social links
[extra.social]
# github = "<github_username>"
# twitter = "<twitter_username>"
# instagram = "<instagram_username>"
# behance = "<behance_username>"
# google_scholar = "<googlescholar_userid>"
# orcid = "<orcid_userid>"
# mastodon = "<mastadon_username>"


# To add google analytics
[extra.analytics]
google = "<your_gtag>"

# To add disqus comments
[extra.commenting]
disqus = "<your_disqus_shortname>"

# To enable mapbox maps
[extra.mapbox]
enabled = true
access_token = "<your_access_token>"
